In [1]:
import pandas as pd

In [3]:
rides = pd.read_csv("/Users/kcarnold/Downloads/2011-capitalbikeshare-tripdata.zip")
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226767 entries, 0 to 1226766
Data columns (total 9 columns):
Duration                1226767 non-null int64
Start date              1226767 non-null object
End date                1226767 non-null object
Start station number    1226767 non-null int64
Start station           1226767 non-null object
End station number      1226767 non-null int64
End station             1226767 non-null object
Bike number             1226767 non-null object
Member type             1226767 non-null object
dtypes: int64(3), object(6)
memory usage: 84.2+ MB

In [5]:
rides['start'] = pd.to_datetime(rides['Start date'])
rides['start'].iloc[0]

Timestamp('2011-01-01 00:01:29')

In [6]:
rides['Member type'].value_counts()

Member     979814
Casual     246949
Unknown         4
Name: Member type, dtype: int64

In [7]:
rides = rides[rides['Member type'] != "Unknown"]

In [8]:
rides['Member type'].value_counts()

Member    979814
Casual    246949
Name: Member type, dtype: int64

In [9]:
del rides["Start station"]
del rides["End station"]

In [11]:
rides.head()

,Duration,Start date,End date,Start station number,End station number,Bike number,Member type,start
0,3548,2011-01-01 00:01:29,2011-01-01 01:00:37,31620,31620,W00247,Member,2011-01-01 00:01:29
1,346,2011-01-01 00:02:46,2011-01-01 00:08:32,31105,31101,W00675,Casual,2011-01-01 00:02:46
2,562,2011-01-01 00:06:13,2011-01-01 00:15:36,31400,31104,W00357,Member,2011-01-01 00:06:13
3,434,2011-01-01 00:09:21,2011-01-01 00:16:36,31111,31503,W00970,Member,2011-01-01 00:09:21
4,233,2011-01-01 00:28:26,2011-01-01 00:32:19,31104,31106,W00346,Casual,2011-01-01 00:28:26

In [12]:
grouped = rides.groupby([rides.start.dt.date, rides.start.dt.hour, rides['Member type']]).size()

In [16]:
grouped.unstack(-1)

Member type       Casual  Member
start      start
2011-01-01 0         3.0    13.0
           1         8.0    30.0
           2         5.0    26.0
           3         3.0     9.0
           4         NaN     1.0
           5         NaN     1.0
           6         2.0     NaN
           7         1.0     2.0
           8         1.0     7.0
           9         8.0     6.0
           10       12.0    22.0
           11       26.0    30.0
           12       29.0    54.0
           13       47.0    47.0
           14       34.0    69.0
           15       40.0    67.0
           16       41.0    50.0
           17       15.0    51.0
           18        9.0    22.0
           19        6.0    27.0
           20       11.0    23.0
           21        3.0    31.0
           22       11.0    17.0
           23       15.0    24.0
2011-01-02 0         4.0    13.0
           1         1.0    15.0
           2         1.0     8.0
           3         2.0     4.0
           4         2.0     1.0
           6         NaN     2.0
...                  ...     ...
2011-12-30 18       19.0   159.0
           19       16.0    93.0
           20       16.0    75.0
           21       11.0    84.0
           22        7.0    77.0
           23       13.0    60.0
2011-12-31 0         7.0    37.0
           1         4.0    30.0
           2         1.0    27.0
           3         1.0    17.0
           4         1.0     9.0
           5         1.0     NaN
           6         1.0     5.0
           7         6.0    13.0
           8         7.0    42.0
           9        18.0    71.0
           10       20.0   108.0
           11       65.0   152.0
           12       93.0   178.0
           13      108.0   200.0
           14      115.0   181.0
           15       89.0   161.0
           16       52.0   139.0
           17       28.0    99.0
           18       13.0    80.0
           19       19.0    70.0
           20        8.0    63.0
           21        2.0    50.0
           22        2.0    34.0
           23        4.0    26.0

[8645 rows x 2 columns]